### ISSUE TITLE
Feature request: Custom delay for each split key press

### ISSUE THREAD

**Issue by NachoPager** [Toufool/Auto-Split#28] opened 2019-05-18 15:05 UTC
For some games its hard to find an image that works for every split (for example fadeouts).
Having the ability to use delays before each split key press would give users more flexibility. That way they could set up a good image 5 seconds before the fadeout (for example), and set the delay to 5 seconds on the split.
It could probably work the same way as custom thresholds or pause times in the split filenames.

Right now I'm planning on using a custom Autohoykey script to setup something like this, but It'd be great to have it as a feature in the actual tool.

**Comment by Toufool** [comment] 2019-07-07 00:10
duplicate of issue https://github.com/Toufool/Auto-Split/issues/23

**Closed by Toufool** 2019-07-07 00:10 UTC
Labels: duplicate
